// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhlofqisrvtozsuoecvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobG9mcWlzcnZ0b3pzdW9lY3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDA4NzksImV4cCI6MjA1OTIxNjg3OX0.aeiF94krQBBx3pkqdbpYqwmiYnaO83HCfXNXn676GOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);